image: rootproject/root:6.22.00-centos7

stages:
  # build with
  - build
  # test run with basic analysis
  - test
  # doxygen
  - docs
  - deploy

compile_gcc:
  stage: build
  before_script:
  script:
    - mkdir build; cd build
    - gcc -v > ../gcc.log
    - cmake3 ../src
    - make 2>&1 | tee -a ../gcc.log
  artifacts:
    paths:
      - ./build/SpatialResol.exe
      - ./build/dEdx.exe
      - gcc.log

build_tests:
  stage: build
  before_script:
    - cd test/
  script:
    - make all
  artifacts:
    paths:
      - test/SR_test.exe
      - test/dEdx_test.exe

# run tests using the binary built before
SpatialResol_raw_test:
  stage: test
  before_script:
    - yum -y install wget
    - wget -q https://cernbox.cern.ch/index.php/s/bntCYWHcPuAZ73K/download
    - mv download input.root
    - export SOFTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/"
  script:
    - ./build/SpatialResol.exe -b -t 0 -i input.root -o Spatial_test_iter0.root -v 1
    - ./build/SpatialResol.exe -b -t 1 -i input.root -o Spatial_test_iter1.root -v 1
    - ./test/SR_test.exe Spatial_test_iter0.root 400;
    - ./test/SR_test.exe Spatial_test_iter1.root 300;
    - ./test/dEdx_test.exe Spatial_test_iter1.root

Spatial_resol_slope_diagonal:
  stage: test
  before_script:
    - yum -y install wget
    - wget -q https://cernbox.cern.ch/index.php/s/ONB1tf842ZEpmGR/download
    - mv download input.root
    - sed -i '23s@.*@cluster = diag@' params/default.ini
    - sed -i '45s@.*@cluster_min  = 52@' params/default.ini
    - export SOFTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/"
  script:
    - ./build/SpatialResol.exe -b -t 0 -i input.root -o Spatial_test_iter0.root -v 1
    - ./build/SpatialResol.exe -b -t 1 -i input.root -o Spatial_test_iter1.root -v 1
    - ./test/SR_test.exe Spatial_test_iter1.root 600;

Spatial_resol_slope_column:
  stage: test
  before_script:
    - yum -y install wget
    - wget -q https://cernbox.cern.ch/index.php/s/rDHRtB56bFqv95x/download
    - mv download input.root
    - sed -i '34s@.*@max_mult = 7@' params/default.ini
    - sed -i '28s@.*@invert  = 1@' params/default.ini
    - export SOFTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/"
  script:
    - ./build/SpatialResol.exe -b -t 0 -i input.root -o Spatial_test_iter0.root -v 1 --end 10000
    - ./build/SpatialResol.exe -b -t 1 -i input.root -o Spatial_test_iter1.root -v 1 --end 10000
    - ./test/SR_test.exe Spatial_test_iter1.root 650;

Spatial_resol_slope_3by1:
  stage: test
  before_script:
    - yum -y install wget
    - wget -q https://cernbox.cern.ch/index.php/s/gbGTuiTLHavF1MG/download
    - mv download input.root
    - sed -i '23s@.*@cluster = 3by1@' params/default.ini
    - sed -i '34s@.*@max_mult = 6@' params/default.ini
    - sed -i '45s@.*@cluster_min  = 31@' params/default.ini
    - export SOFTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/"
  script:
    - ./build/SpatialResol.exe -b -t 0 -i input.root -o Spatial_test_iter0.root -v 1 --end 10000
    - ./build/SpatialResol.exe -b -t 1 -i input.root -o Spatial_test_iter1.root -v 1 --end 10000
    - ./test/SR_test.exe Spatial_test_iter1.root 600;


# documentation, etc.
docs:
  image: rightmesh/ubuntu-doxygen:5.0
  stage: docs
  # when: manual
  before_script:
    - sed -i 's@![Tool structure](doc/doc_html__spatial_resol_ana_8cxx__incl.png)@![Tool structure](d5/da3/_spatial_resol_ana_8hxx__incl.png)@g' README.md
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
      - doc/html
  only:
  - develop

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r doc/html/* .public/
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - develop

