image: rootproject/root:6.22.00-centos7

stages:
  # build with
  - build
  # unittests
  - test
  # test run with expected output from basic analysis
  - validation
  # analyze test + validation coverage
  - coverage
  # doxygen
  - docs
  - deploy

compile_gcc:
  stage: build
  script:
    - mkdir build; cd build
    - gcc -v > ../gcc.log
    - cmake3 ../
    - make 2>&1 | tee -a ../gcc.log
  artifacts:
    paths:
      - build
      - gcc.log

build_tests:
  stage: build
  before_script:
    - cd test/
  script:
    - make all
  artifacts:
    paths:
      - test/SR_test.exe
      - test/dEdx_test.exe


clang:
    stage: test
    before_script:
      - yum install -y llvm-toolset-7-clang-tools-extra
      - . /opt/rh/llvm-toolset-7/enable
      - yum install -y llvm-toolset-7-clang.x86_64
      - curl https://raw.githubusercontent.com/llvm-mirror/clang-tools-extra/master/clang-tidy/tool/run-clang-tidy.py --output /run-clang-tidy.py
      - chmod +x /run-clang-tidy.py
    script:
      - cd build; cmake3 ../
      - /run-clang-tidy.py 2>&1 | tee -a ../clang-tidy.log
    artifacts:
      paths:
        - clang-tidy.log

Google_test:
  stage: test
  script:
    - ./build/Google_tests/Google_Tests_run

# run tests using the binary built before
SpatialResol_raw_test:
  stage: validation
  before_script:
    - yum -y install wget
    - wget -q https://cernbox.cern.ch/index.php/s/bntCYWHcPuAZ73K/download
    - mv download input.root
    - export SOFTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/"
  script:
    - ./build/SpatialResol.exe -b -t 0 -i input.root -o Spatial_test_iter0.root -v 1
    - ./build/SpatialResol.exe -b -t 1 -i input.root -o Spatial_test_iter1.root -v 1
    - ./test/SR_test.exe Spatial_test_iter0.root 400;
    - ./test/SR_test.exe Spatial_test_iter1.root 300;
    - ./test/dEdx_test.exe Spatial_test_iter1.root

Spatial_resol_slope_diagonal:
  stage: validation
  before_script:
    - yum -y install wget
    - wget -q https://cernbox.cern.ch/index.php/s/ONB1tf842ZEpmGR/download
    - mv download input.root
    - sed -i '29s@.*@cluster = diag@' params/default.ini
    - sed -i '51s@.*@cluster_min  = 52@' params/default.ini
    - export SOFTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/"
  script:
    - ./build/SpatialResol.exe -b -t 0 -i input.root -o Spatial_test_iter0.root -v 1
    - ./build/SpatialResol.exe -b -t 1 -i input.root -o Spatial_test_iter1.root -v 1
    - ./test/SR_test.exe Spatial_test_iter1.root 600;

Spatial_resol_slope_column:
  stage: validation
  before_script:
    - yum -y install wget
    - wget -q https://cernbox.cern.ch/index.php/s/rDHRtB56bFqv95x/download
    - mv download input.root
    - sed -i '40s@.*@max_mult = 7@' params/default.ini
    - sed -i '34s@.*@invert  = 1@' params/default.ini
    - export SOFTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/"
  script:
    - ./build/SpatialResol.exe -b -t 0 -i input.root -o Spatial_test_iter0.root -v 1 --end 10000
    - ./build/SpatialResol.exe -b -t 1 -i input.root -o Spatial_test_iter1.root -v 1 --end 10000
    - ./test/SR_test.exe Spatial_test_iter1.root 650;

Spatial_resol_slope_3by1:
  stage: validation
  before_script:
    - yum -y install wget
    - wget -q https://cernbox.cern.ch/index.php/s/gbGTuiTLHavF1MG/download
    - mv download input.root
    - sed -i '29s@.*@cluster = 3by1@' params/default.ini
    - sed -i '40s@.*@max_mult = 6@' params/default.ini
    - sed -i '51s@.*@cluster_min  = 31@' params/default.ini
    - export SOFTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/"
  script:
    - ./build/SpatialResol.exe -b -t 0 -i input.root -o Spatial_test_iter0.root -v 1 --end 10000
    - ./build/SpatialResol.exe -b -t 1 -i input.root -o Spatial_test_iter1.root -v 1 --end 10000
    - ./test/SR_test.exe Spatial_test_iter1.root 600;


coverage:
  stage: coverage
  script:
    - lcov --directory build/ --output-file main_coverage.info -c
    - genhtml main_coverage.info --output-directory out
  artifacts:
    paths:
      - out

# documentation, etc.
docs:
  image: rightmesh/ubuntu-doxygen:5.0
  stage: docs
  # when: manual
  before_script:
    - sed -i '38s@.*@![Tool structure](d5/da3/_spatial_resol_ana_8hxx__incl.png)@g' README.md
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
      - doc/html
  only:
  - develop

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r doc/html/* .public/
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - develop

